# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 573)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: black;\n"
"    color: white;\n"
"    font: 12pt \"Consolas\";\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QTreeView {\n"
"    background-color: rgb(42, 42, 42);\n"
"    alternate-background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: black;\n"
"    alternate-background-color: black;\n"
"    color: white;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.controlButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.controlButton.setObjectName("controlButton")
        self.horizontalLayout.addWidget(self.controlButton)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.interfacesBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.interfacesBox.setObjectName("interfacesBox")
        self.horizontalLayout.addWidget(self.interfacesBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.packetsTreeView = QtWidgets.QTreeView(parent=self.centralwidget)
        self.packetsTreeView.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked)
        self.packetsTreeView.setObjectName("packetsTreeView")
        self.verticalLayout.addWidget(self.packetsTreeView)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Анализатор сетевого траффика"))
        self.controlButton.setText(_translate("MainWindow", "Запуск"))
        self.label.setText(_translate("MainWindow", "Доступные интерфейсы:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
